name: Deploy to Kubernetes

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-image:$(date +%s) .
      - name: Push image to Artifact Registry
        uses: google-github-actions/artifact-registry@v1
        with:
          repository: your-artifact-registry-repository
          images: my-image:$(date +%s)
      - name: Deploy to Kubernetes
        uses: google-github-actions/kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          command: apply
          files: |
            - deployment.yaml
            - service.yaml
