name: Deploy to Google Cloud

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub or Google Container Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=webapp:$(date +%s)
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/$IMAGE_NAME
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Reference the build job by name

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Kubernetes (GKE)
        run: |
          gcloud container clusters get-credentials CLUSTER_NAME --region REGION_NAME
          kubectl apply -f k8s/deployment.yaml
      - name: Expose Application Service
        run: |
          kubectl expose deployment webapp --type=LoadBalancer --port=80 --target-port=8080
