name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_KEY }}

    - name: Build Docker image
      run: docker build -t gcr.io/dev-project-433810/my-webapp .

    - name: Push Docker image
      run: docker push gcr.io/dev-project-433810/my-webapp


      - name: Expose Application Service
        run: |
          kubectl expose deployment webapp --type=LoadBalancer --port=80 --target-port=8080
